### ISSUE TITLE
Charts section updates

### ISSUE THREAD

**Issue by villeingman** [vaadin/elements-page#24]
Charts section should have the version 4.0. 
"Commercial license" section should be changed from "See more" to "See pricing" and link to vaadin.com/pricing.

**Comment by Haprog** [comment]
Now fixed in https://github.com/vaadin/elements-page/commit/4a9640b1a3c3e5b551b66ae1e8cb92a2136ff4cd and deployed to production.

Charts version number should update automatically once vaadin-charts repo starts marking releases properly as GitHub releases: https://github.com/vaadin/vaadin-charts/releases
Currently these don't show up with the API: https://api.github.com/repos/vaadin/vaadin-charts/releases
